### ISSUE TITLE
No module named 'dev.Utils'

### ISSUE THREAD

**Issue by chen10089** [zishuozeng/CLAIRE#1]
from dev.prediction.inference_EC import infer_maxsep
get error：
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 1
----> 1 from dev.prediction.inference_EC import infer_maxsep
      2 import pickle
      3 import numpy as np

File ~/code/CLAIRE/dev/prediction/inference_EC.py:4
      2 import sys
      3 sys.path.append('/root/CLAIRE')
----> 4 from dev.Utils.utils import *
      5 import pandas as pd
      6 import torch.nn as nn

ModuleNotFoundError: No module named 'dev.Utils'

**Comment by chen10089** [comment]
when I use the sys.path.append('/home/chenancheng/code/CLAIRE'), I get an new error:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9c239aa0bbc4> in <module>
----> 1 from dev.prediction.inference_EC import infer_maxsep

~/code/CLAIRE/dev/prediction/inference_EC.py in <module>
      2 import sys
      3 sys.path.append('/home/chenancheng/code/CLAIRE')
----> 4 from dev.utils import *
      5 import pandas as pd
      6 import torch.nn as nn

~/code/CLAIRE/dev/utils/__init__.py in <module>
----> 1 from .evaluate import *
      2 from .utils import *

ModuleNotFoundError: No module named 'dev.utils.evaluate'

**Comment by Billie-0918** [comment]
This issue has been fixed，change ‘Utils’ to ’utils’, change 'from dev.prediction.inference_EC import infer_maxsep' to 'from dev.prediction.inference_EC import inference'

**Comment by chen10089** [comment]
But when I use:
from dev.prediction.inference_EC import infer_maxsep
still get the error:
In [2]: from dev.prediction.inference_EC import infer_maxsep
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[2], line 1
----> 1 from dev.prediction.inference_EC import infer_maxsep

File ~/code/CLAIRE/dev/prediction/inference_EC.py:4
      2 import sys
      3 sys.path.append('/home/chenancheng/code/CLAIRE')
----> 4 from dev.utils import *
      5 import pandas as pd
      6 import torch.nn as nn

File ~/code/CLAIRE/dev/utils/__init__.py:1
----> 1 from .evaluate import *
      2 from .utils import *

ModuleNotFoundError: No module named 'dev.utils.evaluate'

In [3]: from dev.prediction.inference_EC import infer_maxsep
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[3], line 1
----> 1 from dev.prediction.inference_EC import infer_maxsep

File ~/code/CLAIRE/dev/prediction/inference_EC.py:4
      2 import sys
      3 sys.path.append('/home/chenancheng/code/CLAIRE')
----> 4 from dev.utils import *
      5 import pandas as pd
      6 import torch.nn as nn

File ~/code/CLAIRE/dev/utils/__init__.py:1
----> 1 from .evaluate import *
      2 from .utils import *

ModuleNotFoundError: No module named 'dev.utils.evaluate'

**Comment by chen10089** [comment]
I use the new code, solved the error, thank you~
